[package]
name = "mlp-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
mnist = "0.6.0"
ndarray = "0.15.6"
byteorder = "1.3.4"
rand="0.3.14"